-- ADMIN 
CREATE USER VECTOR_USER IDENTIFIED BY <YOUR_DB_PASSWORD> QUOTA UNLIMITED ON USERS;  
GRANT DB_DEVELOPER_ROLE TO VECTOR_USER;  
GRANT CREATE SESSION TO VECTOR_USER;  
GRANT SELECT ANY TABLE ON SCHEMA VECTOR_USER TO VECTOR_USER;  
ALTER SESSION SET CURRENT_SCHEMA = VECTOR_USER;  
-- AS VECTOR_USER
CREATE TABLE VECTOR_USER.VECTOR_STORE (ID VARCHAR2(64) PRIMARY KEY, METADATA VARCHAR(256), CONTENT CLOB, VECTOR_DATA VECTOR(1536, FLOAT64));